var express = require('express');
var router = express.Router();


const glossary_list = [
  { 'id': 1, 'Term': 'Nanotechnology', 'Description': 'Nanotechnology involves manipulating matter at the molecular or atomic level to create new materials, devices, and applications with unique properties (Roco, 2003).', 'reference': 'Roco, M. C. (2003). Broader societal issues of nanotechnology. Journal of Nanoparticle Research, 5(3-4), 181-189.' },
  { 'id': 2, 'Term': 'Virtual Reality', 'Description': 'VR is a computer-generated simulation that immerses users in a three-dimensional environment, usually experienced through specialized headsets and devices ', 'reference': 'Biocca, F. (1992). Communication within Virtual Reality: Creating a Space for Research. Journal of Communication, 42(4), 5-22.' },
  { 'id': 3, 'Term': 'Renewable energy ', 'Description': 'Renewable energy refers to energy sources derived from natural processes that are continually replenished, such as solar, wind, hydropower, geothermal, and biomass', 'reference': 'Jacobson, M. Z., & Delucchi, M. A. (2011). Providing all global energy with wind, water, and solar power, Part I: Technologies, energy resources, quantities and areas of infrastructure, and materials. Energy Policy, 39(3), 1154-1169.' },
  { 'id': 4, 'Term': 'Machine Learning', 'Description': ' Machine learning is an AI technique in which computer systems learn from and improve their performance on tasks without being explicitly programmed, often using statistical approaches', 'reference': 'Mitchell, T. M. (1997). Machine Learning. McGraw Hill.' },
  { 'id': 5, 'Term': 'Internet of Things', 'Description': 'IoT is a network of physical devices, vehicles, appliances, and other objects embedded with sensors, software, and connectivity, enabling them to collect and exchange data', 'reference': 'Atzori, L., Iera, A., & Morabito, G. (2010). The Internet of Things: A survey. Computer Networks, 54(15), 2787-2805.' },
  { 'id': 6, 'Term': 'Gene Editing', 'Description': 'Gene editing is a technique that allows scientists to modify an organisms DNA, enabling precise alterations to genes, potentially offering solutions for genetic diseases and agricultural improvements', 'reference': 'Doudna, J. A., & Sternberg, S. H. (2017). A Crack in Creation: Gene Editing and the Unthinkable Power to Control Evolution. Houghton Mifflin Harcourt.' },
  { 'id': 7, 'Term': 'Cybersecurity', 'Description': 'Cybersecurity involves protecting computer systems, networks, and data from unauthorized access, attacks, and damage to maintain confidentiality, integrity, and availability', 'reference': 'NIST. (2017). NIST Cybersecurity Framework. National Institute of Standards and Technology.' },
  { 'id': 8, 'Term': 'Climate Change', 'Description': ' Climate change refers to the long-term alteration of Earths climate patterns, including global warming caused by human activities such as burning fossil fuels and deforestation', 'reference': 'IPCC. (2014). Climate Change 2014: Synthesis Report. Contribution of Working Groups I, II, and III to the Fifth Assessment Report of the Intergovernmental Panel on Climate Change. Geneva, Switzerland: IPCC.' },
  { 'id': 9, 'Term': 'Blockchain', 'Description': 'Blockchain is a decentralized and distributed digital ledger technology that records transactions across multiple computers in a way that ensures security, transparency, and immutability', 'reference': 'Swan, M. (2015). Blockchain: Blueprint for a New Economy. O Reilly Media.' },
  { 'id': 10, 'Term': 'Artificial Intelligence', 'Description': ' AI refers to the simulation of human intelligence in machines that are programmed to perform tasks requiring human-like cognitive abilities, such as learning, problem-solving, and decision-making', 'reference': 'Russell, S. J., & Norvig, P. (2016). Artificial Intelligence: A Modern Approach (3rd ed.). Pearson.' },
  { 'id': 11, 'Term': 'Big Data', 'Description': '  Big data refers to extremely large and complex datasets that require specialized processing and analysis techniques to extract meaningful insights and patterns', 'reference': 'RLaney, D. (2001). 3D Data Management: Controlling Data Volume, Velocity, and Variety. META Group Research Note, G00166629.' },
  { 'id': 12, 'Term': 'Cloud Computing', 'Description': '  Cloud computing is the delivery of computing services, including storage, processing power, and software, over the internet, allowing users to access resources on-demand without local infrastructure.', 'reference': 'Armbrust, M., Fox, A., Griffith, R., Joseph, A. D., Katz, R. H., Konwinski, A., ... & Zaharia, M. (2010). A view of cloud computing. Communications of the ACM, 53(4), 50-58.' },
  { 'id': 13, 'Term': 'Deep Learning', 'Description': '  Deep learning is a subset of machine learning that involves artificial neural networks with multiple layers, enabling the system to automatically learn hierarchical features from data.', 'reference': 'LeCun, Y., Bengio, Y., & Hinton, G. (2015). Deep learning. Nature, 521(7553), 436-444.' },
  { 'id': 14, 'Term': 'Fintech ', 'Description': ' Fintech, short for financial technology, refers to innovative technologies and solutions that enhance and automate financial services, including banking, payments, lending, and investment.', 'reference': 'PwC. (2017). Redrawing the lines: FinTech’s growing influence on financial services. PwC Global FinTech Report.' },
  { 'id': 15, 'Term': 'Genetic Engineering', 'Description': '  Genetic engineering involves manipulating an organisms genes to introduce specific traits or modifications, often used in biotechnology and agriculture ', 'reference': 'National Academies of Sciences, Engineering, and Medicine. (2016). Gene Drives on the Horizon: Advancing Science, Navigating Uncertainty, and Aligning Research with Public Values. The National Academies Press.' },
  { 'id': 16, 'Term': 'Quantum Computing', 'Description': '  Quantum computing utilizes quantum-mechanical phenomena, such as superposition and entanglement, to perform computations with the potential to solve complex problems more efficiently than classical computers.', 'reference': 'Preskill, J. (2018). Quantum Computing in the NISQ era and beyond. Quantum, 2, 79.' },
  { 'id': 17, 'Term': 'Robotics', 'Description': ' Robotics is the interdisciplinary field that involves the design, construction, operation, and use of robots to perform tasks autonomously or under human control.', 'reference': 'Siciliano, B., & Khatib, O. (Eds.). (2016). Springer Handbook of Robotics. Springer.' },
  { 'id': 18, 'Term': 'Sustainable Development', 'Description': ' Sustainable development refers to the practice of meeting current societal needs without compromising the ability of future generations to meet their own needs, balancing economic, environmental, and social factors.', 'reference': 'United Nations. (1987). Our Common Future: Report of the World Commission on Environment and Development. Oxford University Press.' },
  { 'id': 19, 'Term': 'virtual assistant', 'Description': ' A virtual assistant is an AI-powered software or application that can perform tasks, provide information, and interact with users through natural language processing and other technologies ', 'reference': 'Li, D., Chu, W., & Miao, C. (2020). Virtual Assistant Design and Features: A Literature Review. IEEE Access, 8, 21377-21392.' },
  { 'id': 20, 'Term': '5G', 'Description': '  5G refers to the fifth generation of mobile wireless technology, offering significantly higher data speeds, lower latency, and increased connectivity for a wide range of applications ', 'reference': 'Rappaport, T. S., Heath Jr, R. W., Daniels, R. C., & Murdock, J. N. (2013). Millimeter wave wireless communications. Prentice Hall.' },
  
  
  
  
];



/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'Glossary', glossary: glossary_list });
});

module.exports = router;
